### ISSUE TITLE
Title of Modal Not Displaying

### ISSUE THREAD

**Issue by j3omal** [yogiben/meteor-autoform-modals#23]
Hi There,

I'm a complete novice when it comes to Meteor, so this can totally be user error...

Using the "Insert" example, I have this code in my HTML:

`{{#afModal class="btn btn-xs btn-primary pull-right" collection="Tenants" operation="insert"}} New Tenant {{/afModal}}`

Functionally - it's perfect.  The modal appears and will add to the Tenants collection.  The one issue I have is that the "Title" of the modal is blank, the "prompt" as well (if I were send a value).

It seems as though the "cmDoc" variable is empty.  When the modal appears on screen and I go to the console and type `Session.get("cmTitle");` - I'll see the value "New Tenant".  Yet, the HTML generated for modal title is empty.

Looking at the package code, it looks like the `{{#with cmDoc}}` part of the modal title is prohibiting the title from appearing in my case.  To fix this for me - I added `Session.setDefault('cmDoc', 111);` - where '111' is just a random number - in my .js file.  Just to make sure there is a value for cmDoc.  After I did this, everything works great.  The title and prompt values will now appear.

Just wanted to let you know.  Thanks!

**Comment by mcpackin** [comment]
I also am having this issue, adding ` Session.setDefault('cmDoc', 111); ` does indeed resolve the issue.

Thanks!
