### ISSUE TITLE
Modals not working in yogiben meteor-starter

### ISSUE THREAD

**Issue by MHerszak** [yogiben/meteor-autoform-modals#28]
Hi,

I just started to use your meteor-starter package. I just noticed that the modals are not working with Opera, Firefox and Chrome. I changed to a different Bootstrap 3 Template and I am using INSPINIA (http://wrapbootstrap.com/preview/WB0R5L90S). Could that be a problem? Are there any known issues? Thank you!

Cheers,
Michel

**Comment by yogiben** [comment]
This was a bug. It's been fixed in the latest release.
