### ISSUE TITLE
Error: No such template: afModal after Install

### ISSUE THREAD

**Issue by todda00** [yogiben/meteor-autoform-modals#30]
For some reason when I installed this package, the adModal template is not being included, even though I see the template defined in the repository, when I look in the compiled package code in my app it is not present. When I add the afModal template code to my app directly, it starts working. The autoformModals template is present, but not the afModal.

**Comment by todda00** [comment]
Well as soon as I added the allow functions for the collection this error went away.

**Comment by todda00** [comment]
Spoke too soon, this is an issue, I saw the duplicate template message just after I added the allow functions, but after the next refresh it went back to the way it was, not seeing the afModal template unless its manually in my code.

**Comment by todda00** [comment]
When I cloned the latest from Github it worked - you should publish a new release to atmosphere to make sure the latest code is being pushed.

**Comment by davidmulligan** [comment]
Hi - I have the same problem.  When you cloned from the latest - did you package it up and used instead? Thanks.

**Comment by yogiben** [comment]
New version published. Pls let me know if that fixes it.

**Comment by davidmulligan** [comment]
Hi,

Thanks a million ­ that worked fine.

Superb package ­ you have saved me loads of time.

Thanks

D.

From:  Ben Jones <notifications@github.com>
Reply-To:  yogiben/meteor-autoform-modals
<reply+00a2d006ddf0940a0d4b2f9440599d8193ed14c730e0d60b92cf0000000110e0b6519
2a169ce034ed1a9@reply.github.com>
Date:  Wednesday, 28 January 2015 14:38
To:  yogiben/meteor-autoform-modals
<meteor-autoform-modals@noreply.github.com>
Cc:  David Mulligan <davidmulligan@btopenworld.com>
Subject:  Re: [meteor-autoform-modals] Error: No such template: afModal
after Install (#30)


New version published. Pls let me know if that fixes it.

‹
Reply to this email directly or view it on GitHub
<https://github.com/yogiben/meteor-autoform-modals/issues/30#issuecomment-71
844154> .
