### ISSUE TITLE
Using with jquery-layout, form is not on top and browser full window is not grayed out.

### ISSUE THREAD

**Issue by butlera1** [yogiben/meteor-autoform-modals#32]
Using with the Meteor jquery-layout plug-in appears to be in conflict. See image below. Is there a setting I should use to get the form to appear on top and fully grayed out?

![image](https://cloud.githubusercontent.com/assets/782124/6135396/8261d872-b125-11e4-8dcb-7199bebfef56.png)

**Comment by mpowaga** [comment]
It's a problem with jquery or bootstrap modals not the package.
