### ISSUE TITLE
Window closes immediately.

### ISSUE THREAD

**Issue by Anonyfox** [yogiben/meteor-autoform-modals#4]
I just tried your example code with the insert-button on one of my collections, the window slides in onClick, but the moment the animations ends, it's hidden again. 

tried on Meteor version 1.0 with latest version of iron-router, collection2, etc.

**Comment by MurWade** [comment]
This is happening to me too. no error messages.

**Comment by MurWade** [comment]
**Now it works for me!**

I guess the problem for me was that I also added boostrap.js file in `client/lib/compatibility` folder.
Becuase i didnt think `mizzao:bootstrap-3 ` package would add that for me.

**Comment by kamil7732** [comment]
I was able to reproduce the error.
When I tried to manually run .modal('show'); from console it worked.
Finally I removed modal library from bootstrap 3 (I use nemo64:bootstrap). After that everything works just fine.
