### ISSUE TITLE
aldeed:autoform is outdated on this package

### ISSUE THREAD

**Issue by Ajaxsoap** [yogiben/meteor-autoform-modals#41]
Potentially incompatible change required to top-level dependency:
aldeed:autoform 4.2.2, was 5.1.2.
Constraints on package "aldeed:autoform":
* aldeed:autoform@4.2.2 <- yogiben:autoform-modals 0.3.2

**Comment by roelvan** [comment]
+1

**Comment by voidale** [comment]
+1

**Comment by derdaumen** [comment]
+1

**Comment by harryhurry** [comment]
+1

**Comment by kepler** [comment]
+1

**Comment by MarcoTribuz** [comment]
+1

**Comment by mpowaga** [comment]
Latest version updates the autoform dependency.

**Comment by roelvan** [comment]
Awesome, thanks!
