### ISSUE TITLE
Add hook to remove form?

### ISSUE THREAD

**Issue by jamiecollinson** [yogiben/meteor-autoform-modals#43]
I'd like to add an onSuccess hook to a remove form, but as far as I can tell this isn't currently possible as adding a formId isn't respected for operation="remove".

Am I missing something really obvious? I have it working fine for insert and update forms.

**Comment by mpowaga** [comment]
It's hard to provide a callback because communication between modal and trigger button is done through session variables and it's not possible to assign a function to session variable.

**Comment by jamiecollinson** [comment]
Awesome thanks. I'm a bit new to meteor & atmosphere, is there a way to force an update to 0.3.4?

I've tried `meteor add yogiben:autoform-modals@0.3.4` but that gives a `no such version` error. Do you need to manually publish to atmosphere before it's available there?

**Comment by mpowaga** [comment]
Seems `0.3.4` wasn't published on atmosphere somehow. But `0.3.5` is and you can update to this version.
