### ISSUE TITLE
Problem with unbinding body handers

### ISSUE THREAD

**Issue by datenarbeit** [yogiben/meteor-autoform-modals#47]
Hi there,
first of all: great job! 
but: I had a problem using your package. in my case it leads to problems when you unbind all body click events on destroy with: Template.autoformModals.destroyed = -> $('body').unbind 'click'

I patchhed this for my needs to 
'click .af-model': (e, t) ->
....
Template.autoformModals.destroyed = -> $('.af-model').unbind 'click'

and extended the afModal template with class="{{class}} af-modal".

now it works perfectly for me. maybe this could help others too, facing similar problems, like i had.

Best,
thomas

**Comment by mpowaga** [comment]
Nice find! It looks to be unnecessary since we don't bind click handler to body anywhere in the code. So I just deleted it.
