### ISSUE TITLE
Form error messages still persist when insert (but not really insert data) then update.

### ISSUE THREAD

**Issue by balll** [yogiben/meteor-autoform-modals#49]
Form error messages still persist when insert (but not really insert data) then update.

To reproduce

1. Click the add button (Use afModal operation=insert)
2. Click create without input any data. ![screen shot 2558-07-06 at 2 37 53 am](https://cloud.githubusercontent.com/assets/3858431/8513106/1be8a2da-2388-11e5-91ab-3095af45d7cd.png)
3. Close the modal without insert any data.
4. Click the update button (Use afModal operation=update on some existing items) ![screen shot 2558-07-06 at 2 37 58 am](https://cloud.githubusercontent.com/assets/3858431/8513121/89c901b4-2388-11e5-8884-abfbeda2a974.png)

As you can see. The error messages still persist.

**Comment by mpowaga** [comment]
Fixed in this [commit](https://github.com/yogiben/meteor-autoform-modals/commit/cc79d8e196444dfef144f567131344b49bf04bb3).
