### ISSUE TITLE
quickForm vs autoForm

### ISSUE THREAD

**Issue by j20** [yogiben/meteor-autoform-modals#50]
This package appears roughly equivalent to using autoform's quickform (`{{> quickForm id="demo" schema=schema}}`). Does this package support declaring the form using autoform's longer style that offers more control specifying what fields are used? Such as:

	{{#autoForm id="demo" schema=schema}}
	  {{> afQuickFields}}
	  <div>
	    <button type="submit">Submit</button>
	  </div>
	{{/autoForm}}

**Comment by mpowaga** [comment]
Nope. It would be pretty much the same as creating a new modal in one place and trigger button in other.
