### ISSUE TITLE
Callback hooks not getting triggered. 

### ISSUE THREAD

**Issue by pbibalan** [yogiben/meteor-autoform-modals#64]
I am unable to trigger autoform callback hooks. They work fine with autoForm and quickForm but not with afModal and I can't figure out why they are not working. Here's what I have: 
```
{{#afModal collection="Items" operation="insert" formId='itemForm'}}
          Add Item
 {{/afModal}}
```
and
```
 AutoForm.hooks({
    itemForm: {
        onSubmit: function (doc) {
          console.log("callback");
          return false;
      }
  }
```
or 
```
AutoForm.addHooks(['itemForm'], hooksObject);
```
Versions: 
```
yogiben:autoform-modals@0.3.8
aldeed:autoform@5.5.1
```

**Comment by mkarliner** [comment]
I think I am having the same problem.

**Comment by pbibalan** [comment]
Problem for me was that onSubmit was not getting triggered at all (event with normal auto form). I changed it to before: insert: and it works fine. 
```
AutoForm.hooks 
  itemForm: 
    before: insert: (doc, template) ->
```
