### ISSUE TITLE
Delete form: onSuccess callback is fired right away

### ISSUE THREAD

**Issue by noahsw** [yogiben/meteor-autoform-modals#79]
My helpers look like this:
```
Template.docEdit.helpers({
  onRemoveSuccess: () => FlowRouter.go('/'),
});
```

And template:
```
{{#afModal class="btn btn-danger" collection="Docs" operation="remove" doc=doc._id onSuccess=onRemoveSuccess}}
  Delete
{{/afModal}}

```

With some logging statements, I can see that `onRemoveSuccess` is called as soon as the template is rendered (before the modal appears). Any ideas why?

**Comment by noahsw** [comment]
Wrapping the `onRemoveSuccess` method in a function resolved the issue. For example:

```
onRemoveSuccess: () => {
  return () => {
    $('.modal-backdrop').hide(); // https://github.com/yogiben/meteor-autoform-modals/issues/65
    FlowRouter.go('/');
  }
},
```

**Comment by zcrowe** [comment]
Hello :)

I now realise an issue I've raised here: https://github.com/yogiben/meteor-autoform-modals/issues/86 has been stumbled upon before.

However @noahsw I'm not sure I understand your solutions ...is onRemoveSuccess an undocumented hook?

**Comment by zcrowe** [comment]
@noahsw gah - never mind, I now sort of get how this works, my original issues still stands though, as I need an attribute of the document being deleted. Any tips?
